version: '3.8'

services:
  # Основной backend сервис
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: triplan-backend
    environment:
      - DB_PATH=/app/data/triplan.db
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - ADMIN_MIGRATION_TOKEN=${ADMIN_MIGRATION_TOKEN:-your-admin-token}
    volumes:
      - ./data:/app/data  # Монтируем директорию с данными
      - ./logs:/app/logs  # Монтируем директорию для логов
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - triplan-network

  # Контейнер для миграций
  migration:
    build: 
      context: ./backend
      dockerfile: Dockerfile.migration
    container_name: triplan-migration
    environment:
      - DB_PATH=/app/data/triplan.db
      - BACKUP_DIR=/app/backups
      - VALIDATE_ONLY=${VALIDATE_ONLY:-false}
    volumes:
      - ./data:/app/data  # Монтируем ту же директорию с данными
      - ./backups:/app/backups  # Монтируем директорию для бэкапов
    command: migrate
    restart: "no"  # Запускаем только один раз
    depends_on:
      - backend
    networks:
      - triplan-network

  # Nginx для reverse proxy (опционально)
  nginx:
    image: nginx:alpine
    container_name: triplan-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro  # SSL сертификаты
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - triplan-network

networks:
  triplan-network:
    driver: bridge

volumes:
  data:
    driver: local
  backups:
    driver: local
  logs:
    driver: local
